from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Any

from ..shared.powershell_partials import inline_powershell_tools


def powershell_single_quoted(value: Any) -> str:
    text = "" if value is None else str(value)
    return "'" + text.replace("'", "''") + "'"


def powershell_bool_literal(value: bool) -> str:
    return "$true" if value else "$false"


def normalize_line_endings(text: str) -> str:
    return re.sub(r"\r\n|\n|\r", "\r\n", text or "")


def safe_file_name_part(value: str) -> str:
    cleaned = str(value or "").strip()
    if not cleaned:
        return "unknown"

    cleaned = re.sub(r'[<>:"/\\|?*\x00-\x1f]+', "-", cleaned)
    cleaned = re.sub(r"\s+", "-", cleaned)
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "-", cleaned).strip("-")
    return cleaned or "unknown"


def resolve_template_path(app_dir: Path) -> Path:
    candidates = [
        app_dir / "script_builders" / "user_lockdown" / "template_user_lockdown.ps1",
        Path(__file__).resolve().parent / "template_user_lockdown.ps1",
    ]

    for candidate in candidates:
        if candidate.exists():
            return candidate
    return candidates[0]


def new_user_lockdown_script_file_name(*, client: str, user_lookup: str, ticket_number: str) -> str:
    return "Lockdown-{0}-{1}-{2}.ps1".format(
        safe_file_name_part(client),
        safe_file_name_part(ticket_number),
        safe_file_name_part(user_lookup),
    )


def new_user_lockdown_script(
    *,
    template_path: Path,
    client: str,
    user_lookup: str,
    ticket_number: str,
    run_adsync: bool,
    check_email_rules: bool,
    dry_run: bool,
    force: bool,
) -> str:
    if not template_path.exists():
        raise FileNotFoundError(f"Template script was not found: {template_path}")
    if not client.strip():
        raise ValueError("Client is required.")
    if not user_lookup.strip():
        raise ValueError("User lookup is required.")

    template = template_path.read_text(encoding="utf-8-sig")
    template = inline_powershell_tools(template, template_path.parents[2])
    generated_at = datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S %z")
    config_block = f"""# -------------------------
# Generated by Stuff Opener Script Builders on {generated_at}.
# -------------------------

$Client = {powershell_single_quoted(client)}
$UserLookup = {powershell_single_quoted(user_lookup)}
$TicketNumber = {powershell_single_quoted(ticket_number)}

# Run options.
$RunADSync = {powershell_bool_literal(run_adsync)}
$CheckEmailRules = {powershell_bool_literal(check_email_rules)}
$DryRun = {powershell_bool_literal(dry_run)}
$Force = {powershell_bool_literal(force)}
"""

    top_block_pattern = (
        r"(?ms)# -------------------------\r?\n"
        r"# Fill these in per ticket\.\r?\n"
        r"# -------------------------\r?\n"
        r".*?(?=\r?\n# -------------------------\r?\n# 0\.5\. Prep work:)"
    )
    script, replacement_count = re.subn(top_block_pattern, config_block, template, count=1)
    if replacement_count != 1:
        raise ValueError("Could not find the top ticket config block in the template.")

    return normalize_line_endings(script)
