from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Any

from ..shared.powershell_partials import inline_powershell_tools


def powershell_single_quoted(value: Any) -> str:
    text = "" if value is None else str(value)
    return "'" + text.replace("'", "''") + "'"


def powershell_bool_literal(value: bool) -> str:
    return "$true" if value else "$false"


def normalize_line_endings(text: str) -> str:
    return re.sub(r"\r\n|\n|\r", "\r\n", text or "")


def safe_file_name_part(value: str) -> str:
    cleaned = str(value or "").strip()
    if not cleaned:
        return "unknown"

    cleaned = re.sub(r'[<>:"/\\|?*\x00-\x1f]+', "-", cleaned)
    cleaned = re.sub(r"\s+", "-", cleaned)
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "-", cleaned).strip("-")
    return cleaned or "unknown"


def resolve_template_path(app_dir: Path) -> Path:
    candidates = [
        app_dir / "script_builders" / "user_new" / "template_user_new.ps1",
        Path(__file__).resolve().parent / "template_user_new.ps1",
    ]

    for candidate in candidates:
        if candidate.exists():
            return candidate
    return candidates[0]


def new_user_script_file_name(*, client: str, first_name: str, last_name: str) -> str:
    return "NewUser-{0}-{1}-{2}.ps1".format(
        safe_file_name_part(client),
        safe_file_name_part(first_name),
        safe_file_name_part(last_name),
    )


def new_user_script(
    *,
    template_path: Path,
    client: str,
    first_name: str,
    last_name: str,
    copy_after_lookup: str,
    sam_account_name: str,
    user_principal_name: str,
    target_ou: str,
    title: str,
    department: str,
    description: str,
    manager_lookup: str,
    mapped_drive_letters: str,
    run_adsync: bool,
    must_change_password_at_next_logon: bool,
    dry_run: bool,
    force: bool,
    resume_existing_user: bool,
    resume_user_lookup: str,
    poll_seconds: int,
    poll_attempts: int,
) -> str:
    if not template_path.exists():
        raise FileNotFoundError(f"Template script was not found: {template_path}")
    if not client.strip():
        raise ValueError("Client is required.")
    if not first_name.strip():
        raise ValueError("First name is required.")
    if not last_name.strip():
        raise ValueError("Last name is required.")
    if poll_seconds < 1:
        raise ValueError("Poll seconds must be at least 1.")
    if poll_attempts < 1:
        raise ValueError("Poll attempts must be at least 1.")

    template = template_path.read_text(encoding="utf-8-sig")
    template = inline_powershell_tools(template, template_path.parents[2])
    generated_at = datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S %z")
    config_block = f"""# -------------------------
# Generated by Stuff Opener Script Builders on {generated_at}.
# -------------------------

$Client = {powershell_single_quoted(client)}
$FirstName = {powershell_single_quoted(first_name)}
$LastName = {powershell_single_quoted(last_name)}
$CopyAfterLookup = {powershell_single_quoted(copy_after_lookup)}

# Optional identity/location overrides. Leave blank to resolve interactively.
$SamAccountName = {powershell_single_quoted(sam_account_name)}
$UserPrincipalName = {powershell_single_quoted(user_principal_name)}
$TargetOU = {powershell_single_quoted(target_ou)}
$AdObjectName = ''

# Optional attributes for the new AD user.
$Title = {powershell_single_quoted(title)}
$Department = {powershell_single_quoted(department)}
$Description = {powershell_single_quoted(description)}
$ManagerLookup = {powershell_single_quoted(manager_lookup)}
$MappedDriveLetters = {powershell_single_quoted(mapped_drive_letters)}

# Run options.
$RunADSync = {powershell_bool_literal(run_adsync)}
$MustChangePasswordAtNextLogon = {powershell_bool_literal(must_change_password_at_next_logon)}
$DryRun = {powershell_bool_literal(dry_run)}
$Force = {powershell_bool_literal(force)}
$ResumeExistingUser = {powershell_bool_literal(resume_existing_user)}
$ResumeUserLookup = {powershell_single_quoted(resume_user_lookup)}
$PollSeconds = {poll_seconds}
$PollAttempts = {poll_attempts}
"""

    top_block_pattern = (
        r"(?ms)# -------------------------\r?\n"
        r"# Fill these in per ticket\.\r?\n"
        r"# -------------------------\r?\n"
        r".*?(?=\r?\n# -------------------------\r?\n# 0\.5\. Prep work:)"
    )
    script, replacement_count = re.subn(top_block_pattern, config_block, template, count=1)
    if replacement_count != 1:
        raise ValueError("Could not find the top ticket config block in the template.")

    return normalize_line_endings(script)
